### ISSUE TITLE
compatibility issues, the CJS build of Vite's Node API is deprecated

### ISSUE THREAD

**Issue by liaohongxing** [iGoodie/vite-plugin-react-rich-svg#1]
Compatibility issue, after the latest v5.1 introduces this plug-in, it prompts that the cjs api is outdated

```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```

![20240226093118](https://github.com/iGoodie/vite-plugin-react-rich-svg/assets/35255844/5bbd4851-1fc4-457e-903d-f4ded206fd6a)

**Comment by iGoodie** [comment]
Oh totally my bad! CJS is not supported I see. Thanks for reporting! 🎉 
I'll fix this next free time I have!
