### ISSUE TITLE
Unable to Load an Altered SVG

### ISSUE THREAD

**Issue by dysbulic** [iGoodie/vite-plugin-react-rich-svg#4]
I've been making edits to my SVG *(being imported using the `?raw` modifier)*, & when I reload the page I can't get the new version to load.

I've tried & failed to find where the value is being cached. I cleared the application data in the developer tools & removed `node_modules/.cache/` & restarted the dev server to no avail.

Having something about this in the `README` would sure be nice. 😸

**Comment by iGoodie** [comment]
Wops I never realized there was an internal cache of things being transformed. Perhaps it's because I implemented `?raw` modifier using the `load` feature. I'll fix this!

Thanks for letting me know! 😁  🎉
