### ISSUE TITLE
SVGO

### ISSUE THREAD

**Issue by Leytek** [iGoodie/vite-plugin-react-rich-svg#5]
Seems like SVGO only works when svg is imported as a component. Not raw or url or base64. It is possible to change this? I what to import an optimized svg as raw text.

**Comment by iGoodie** [comment]
Oh what an oversight! Thanks for creating the issue :)
I'll add `rawLoaderOptions` and `base64LoaderOptions` just like `componentLoaderOptions`!

**Comment by iGoodie** [comment]
Resolved by c967e4c

**Comment by iGoodie** [comment]
Resolved by c967e4c
